apiVersion: v1
kind: Service
metadata:
  name: liveness-service
spec:
  type: NodePort
  selector:
    app: liveness
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-deployment
spec:
  selector:
    matchLabels:
      app: liveness
  replicas: 1
  template:
    metadata:
      labels:
        app: liveness
    spec:
      containers:
      - name: liveness
        env: 
        - name: version
          value: '9'
        image: liveness
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
          - containerPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: liveness-ingress
spec:
  rules:
  - host: liveness.info
    http:
      paths:
      - path: /
        backend:
          serviceName: liveness-service
          servicePort: 8080
