apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: liveness
    imagePullPolicy: Never
    livenessProbe:
      httpGet:
        path: /liveness
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
